version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8510:8501"
    restart: unless-stopped
    environment:
      # SMTP Configuration
      - SMTP_HOST=10.103.30.200
      - SMTP_PORT=2727
      - SMTP_USER=bonjour
      - SMTP_PASSWORD=ELp7iR2xb7za
      - SMTP_FROM_EMAIL=info@v6securite.fr
